### ISSUE TITLE
create store button

### ISSUE THREAD

**Issue by asnb1234** [Developer-Mike/FN-Bot#10]
the bot is wonderful, congratulations, but could you create a button to create a store without needing the time? the schedule arrives.. and it says new store found... then it's like 5 minutes, it could be faster, you know

**Comment by Developer-Mike** [comment]
The image generation process takes 2.7 seconds (average) for me 🤷🏻‍♂️. What device are you using?

**Comment by asnb1234** [comment]
estou usando um dell g15 com windows , eu sempre ligo 5 minutos antes do horario da loja mais demora mais de 5 min aqui

**Comment by asnb1234** [comment]
whatsapp? te mostro melhor.... eu tambem tenho umas ideias
