### ISSUE TITLE
Some bundles last seen was wrong. As an example, below image, Double agent pack last seen yesterday but it shows 473 days..

### ISSUE THREAD

**Issue by ThiliX** [Developer-Mike/FN-Bot#13]
![image](https://github.com/Developer-Mike/FN-Bot/assets/77280722/ff7fa6bb-2605-4fc9-af78-a93af66a14c3)

**Comment by Developer-Mike** [comment]
That is a problem with the API (fortniteapi.io)... Nothing I can do about it.

**Comment by ThiliX** [comment]
Oh ok! Can you make this using fortniteapi.com API?

**Comment by Developer-Mike** [comment]
According to my experience, fortniteapi.com is less reliable. In the past, I even rewrote the bot to use fortniteapi.io.

**Comment by ThiliX** [comment]
Oh ok!!

**Comment by ThiliX** [comment]
I have little problem about the order of images. When downloading images to temp folder, it are downloaded in the correct order as API, but when merging images, the order is lost. Please fix this if u can :)

**Comment by Developer-Mike** [comment]
I'll fix it when I have time.

**Comment by ThiliX** [comment]
Ok!
