### ISSUE TITLE
An issue about images merging

### ISSUE THREAD

**Issue by ThiliX** [Developer-Mike/FN-Bot#14]
Hello, After your update, the images are merging in the same order as before. Check it out if you can :)
![shop_2023-10-02](https://github.com/Developer-Mike/FN-Bot/assets/77280722/8156b132-03ca-4165-a9d4-38077b6d896b)

**Comment by Developer-Mike** [comment]
This is the correct order?!

**Comment by ThiliX** [comment]
Can you change the order like this (the last one as Double Agent Pack)
![F7ZJA-hWMAA1F9I](https://github.com/Developer-Mike/FN-Bot/assets/77280722/fb79c10c-b2a8-485d-8687-c2b3f48c2de8)
