### ISSUE TITLE
get quests

### ISSUE THREAD

**Issue by jose89fcb** [Developer-Mike/FN-Bot#17]
Would you also know how to obtain the missions? For example
thank you so much!

![image](https://github.com/user-attachments/assets/c5b7e692-1ce2-4921-8aeb-cedf719c7f33)

**Comment by Developer-Mike** [comment]
This was the initial goal of the vbucks alert function. Unfortunately, the api only provides a mission id. To get the corresponding mission text, you need to decompile the game. This would massively increase the difficulty and thus won't be implemented.
