### ISSUE TITLE
Again hangs

### ISSUE THREAD

**Issue by papaformigas** [Developer-Mike/FN-Bot#5]
Hi Mike the bot was working without issues and all of a sudden it started hanging in the beguinning as before.. Doesnt get the  "New Shop Detected". It stops when it load the three modules... I uncommented the #12 as you told me before but still hangs..nothing happens...

**Comment by Developer-Mike** [comment]
The bot is built for running all the time. It's probably not a hang, but instead, no new shop got detected. If you want to run it anyway, just uncommon this line:  https://github.com/Developer-Mike/FN-Bot/blob/aab3b8a87c4b037e15ffe3db8671ae8dd427f40e/main.py#L12

**Comment by papaformigas** [comment]
with that alteration get the same.. hangs....

**Comment by papaformigas** [comment]
Having uncomment out at main.py
12  schedule.run_all() 

I get the shop to ghenerate but get these errors.. but shop is generated.. 
Hoiw can i generate the shoip anytime?

Assets path: C:\Fortnite\FN-Bot-main\assets
Initialized module: ShopModule
Traceback (most recent call last):
  File "C:\Fortnite\FN-Bot-main\helpers\exception_helper.py", line 8, in wrapper
    return job_func(self, *args, **kwargs)
  File "C:\Fortnite\FN-Bot-main\shop\shop.py", line 35, in update
    if not self._has_new_shop(shop_uid): raise Exception("No new shop detected")
Exception: No new shop detected

Initialized module: LeaksModule
Traceback (most recent call last):
  File "C:\Fortnite\FN-Bot-main\helpers\exception_helper.py", line 8, in wrapper
    return job_func(self, *args, **kwargs)
  File "C:\Fortnite\FN-Bot-main\shop\shop.py", line 35, in update
    if not self._has_new_shop(shop_uid): raise Exception("No new shop detected")
Exception: No new shop detected

Traceback (most recent call last):
  File "C:\Fortnite\FN-Bot-main\helpers\exception_helper.py", line 8, in wrapper
    return job_func(self, *args, **kwargs)
  File "C:\Fortnite\FN-Bot-main\shop\shop.py", line 35, in update
    if not self._has_new_shop(shop_uid): raise Exception("No new shop detected")
Exception: No new shop detected

Initialized module: VBucksModule
Traceback (most recent call last):
  File "C:\Fortnite\FN-Bot-main\helpers\exception_helper.py", line 8, in wrapper
    return job_func(self, *args, **kwargs)
  File "C:\Fortnite\FN-Bot-main\shop\shop.py", line 35, in update
    if not self._has_new_shop(shop_uid): raise Exception("No new shop detected")
Exception: No new shop detected

Traceback (most recent call last):
  File "C:\Fortnite\FN-Bot-main\helpers\exception_helper.py", line 8, in wrapper
    return job_func(self, *args, **kwargs)
  File "C:\Fortnite\FN-Bot-main\shop\shop.py", line 35, in update
    if not self._has_new_shop(shop_uid): raise Exception("No new shop detected")
Exception: No new shop detected

Traceback (most recent call last):
  File "C:\Fortnite\FN-Bot-main\helpers\exception_helper.py", line 8, in wrapper
    return job_func(self, *args, **kwargs)
  File "C:\Fortnite\FN-Bot-main\shop\shop.py", line 35, in update
    if not self._has_new_shop(shop_uid): raise Exception("No new shop detected")
Exception: No new shop detected

Traceback (most recent call last):
  File "C:\Fortnite\FN-Bot-main\helpers\exception_helper.py", line 8, in wrapper
    return job_func(self, *args, **kwargs)
  File "C:\Fortnite\FN-Bot-main\shop\shop.py", line 35, in update
    if not self._has_new_shop(shop_uid): raise Exception("No new shop detected")
Exception: No new shop detected

Posting. (None, Novos Alertas de Missões de V-Bucks para o Salve o Mundo - {date}!\n\nPlankerton: 30\nTwine Peaks: 40\n\n#Fortnite)
Post complete.

**Comment by papaformigas** [comment]
Any help Mike?

**Comment by Developer-Mike** [comment]
As the error says, the shop hasn't updated. If you want to generate the same image again, either delete the last_shop_uid.p file or delete [this line](https://github.com/Developer-Mike/FN-Bot/blob/aab3b8a87c4b037e15ffe3db8671ae8dd427f40e/shop/shop.py#L35) for a permanent change.

**Comment by papaformigas** [comment]
Before when i used to run the boit i would get the Shop posted, the Leaks posted if available and the Vbucks.. now i get this... i think it is not normal...

C:\Fortnite\FN-Bot-main>py -3 main.py
Assets path: C:\Fortnite\FN-Bot-main\assets
Initialized module: ShopModule
New shop detected!
Generated 130 items from the 2023-04-13 item shop.
Compressed image to 1732452 bytes. Took 0.0 seconds.
Shop generated successfully!
Posting. (C:\Fortnite\FN-Bot-main\shop\result\shop_2023-04-13.jpg, LOJA DE ITENS - 13/04/2023\n\n#Fortnite)
Post complete.
Initialized module: LeaksModule
New shop detected!
Generated 130 items from the 2023-04-13 item shop.
Compressed image to 1732452 bytes. Took 0.0 seconds.
Shop generated successfully!
Posting. (C:\Fortnite\FN-Bot-main\shop\result\shop_2023-04-13.jpg, LOJA DE ITENS - 13/04/2023\n\n#Fortnite)
Post complete.
Initialized module: VBucksModule
New shop detected!
Generated 130 items from the 2023-04-13 item shop.
Compressed image to 1732452 bytes. Took 0.0 seconds.
Shop generated successfully!
Posting. (C:\Fortnite\FN-Bot-main\shop\result\shop_2023-04-13.jpg, LOJA DE ITENS - 13/04/2023\n\n#Fortnite)
Post complete.

**Comment by Developer-Mike** [comment]
This is the normal behavior.
