### ISSUE TITLE
cant run the bot

### ISSUE THREAD

**Issue by papaformigas** [Developer-Mike/FN-Bot#7]
HI, since yesterday i am having issues with the bot...

Many errors and trhsi one:

"Error: None is not a valid image"

Yesterday i got another error...

Do you have a solution?

**Comment by Developer-Mike** [comment]
This error occurs when the image is not available on the API side. If you want to ensure that every image is correctly displayed, set `CONTINUE_ON_CORRUPTED_IMAGE` to `false` in the `.env` file.
