### ISSUE TITLE
Old leaks always

### ISSUE THREAD

**Issue by papaformigas** [Developer-Mike/FN-Bot#8]
Hey Mike,

Why I am always getting very old leaks images?

Yesterday I go a lot of black images with only the title and they were upcoming cosmetics, but after some hours i started getting old cosmetic images and not the new ones...

Why this happens??

Another question: is it now possible to add a title to the item shop?

**Comment by Developer-Mike** [comment]
There was a bug in the API. So nothing I can change 🤷🏻.
And there is no way to add a title at the moment. You could add one by yourself tho.
